#!/bin/bash
# QMD Setup Script - Initialize local search for the wiki
# Run this once to set up qmd search engine

set -e

WIKI_DIR="$(cd "$(dirname "$0")/.." && pwd)"
QMD_DIR="$WIKI_DIR/.qmd"

echo "Setting up QMD search engine for wiki..."

# Check if qmd is installed
if ! command -v qmd &> /dev/null; then
    echo "Installing qmd..."
    npm install -g @tobilu/qmd
fi

# Initialize qmd config
mkdir -p "$QMD_DIR"

cat > "$QMD_DIR/qmd.yml" << 'EOF'
# QMD Configuration for Second Brain Wiki
# Generated by tools/scripts/setup-qmd.sh

collections:
  wiki:
    path: ../wiki
    pattern: "**/*.md"
    ignore:
      - "_templates/**"
      - "index.md"
      - "log.md"
    
  raw:
    path: ../raw
    pattern: "**/*"
    ignore:
      - "inbox/**"

default_collection: wiki

# Optional: Add context to help search understand content structure
context:
  - path: qmd://wiki/sources
    description: "Ingested source summaries with key claims"
  - path: qmd://wiki/entities
    description: "People, organizations, tools, and places"
  - path: qmd://wiki/concepts
    description: "Methods, theories, and ideas"
  - path: qmd://wiki/topics
    description: "Thematic syntheses across multiple sources"
  - path: qmd://wiki/syntheses
    description: "Cross-topic analyses and theses"
  - path: qmd://wiki/comparisons
    description: "Side-by-side comparisons"
  - path: qmd://wiki/queries
    description: "Preserved Q&A artifacts from user questions"
EOF

echo "QMD config written to $QMD_DIR/qmd.yml"

# Create the index
echo "Creating search index..."
cd "$QMD_DIR"
qmd collection add . --name wiki 2>/dev/null || true
qmd update

# Generate embeddings for semantic search
echo "Generating embeddings (this may take a minute on first run)..."
qmd embed

echo ""
echo "QMD setup complete!"
echo ""
echo "Usage:"
echo "  qmd search \"query\"           # BM25 keyword search"
echo "  qmd vsearch \"query\"          # Vector semantic search"
echo "  qmd query \"query\"            # Hybrid search (best quality)"
echo "  qmd query \"query\" --json    # JSON output for LLM"
echo ""
echo "For MCP integration, add this to your AI config:"
echo '  { "command": "qmd", "args": ["mcp"] }'