#!/usr/bin/env python3
"""Utilities for maintaining a markdown-based LLM wiki."""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "wiki"

IGNORE_DIRS = {"_templates", ".obsidian"}
IGNORE_FILES = {"index.md", "log.md"}
SPECIAL_LINK_TARGETS = {"index", "log", "home", "category", "page-name", "path", "to"}


@dataclass
class Page:
    path: Path
    rel: Path
    frontmatter: dict[str, str]
    body: str
    text: str
    links: list[str]

    @property
    def title(self) -> str:
        title = self.frontmatter.get("title", "").strip()
        if title:
            return title
        return slug_to_title(self.rel.stem)

    @property
    def summary(self) -> str:
        summary = self.frontmatter.get("summary", "").strip()
        if summary:
            return summary
        return first_paragraph(self.body)

    @property
    def updated(self) -> str:
        return self.frontmatter.get("updated", "")

    @property
    def category(self) -> str:
        if len(self.rel.parts) == 1:
            return "root"
        return self.rel.parts[0]


def slug_to_title(slug: str) -> str:
    return re.sub(r"[-_]+", " ", slug).strip().title()


def first_paragraph(text: str) -> str:
    lines = text.splitlines()
    in_code = False
    for raw in lines:
        line = raw.strip()
        if line.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if not line:
            continue
        if line.startswith("#"):
            continue
        if line.startswith("-"):
            continue
        return line[:220]
    return "No summary available."


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    normalized = text.replace("\r\n", "\n")
    if not normalized.startswith("---\n"):
        return {}, text
    end = normalized.find("\n---\n", 4)
    if end == -1:
        return {}, text
    block = normalized[4:end]
    body = normalized[end + 5 :]
    result: dict[str, str] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip()
    return result, body


WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")


def extract_wikilinks(text: str) -> list[str]:
    result = []
    in_code = False
    for line in text.splitlines():
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        for match in WIKILINK_RE.finditer(line):
            result.append(match.group(1).strip())
    return result


def wiki_files() -> list[Path]:
    files: list[Path] = []
    for path in sorted(WIKI_DIR.rglob("*.md")):
        rel = path.relative_to(WIKI_DIR)
        if any(part in IGNORE_DIRS for part in rel.parts):
            continue
        files.append(path)
    return files


def load_page(path: Path) -> Page:
    text = path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    links = extract_wikilinks(text)
    return Page(
        path=path,
        rel=path.relative_to(WIKI_DIR),
        frontmatter=fm,
        body=body,
        text=text,
        links=links,
    )


def list_content_pages() -> list[Page]:
    pages: list[Page] = []
    for path in wiki_files():
        if path.name in IGNORE_FILES:
            continue
        pages.append(load_page(path))
    return pages


def page_ref(page: Page) -> str:
    rel = page.rel.with_suffix("").as_posix()
    return f"[[{rel}|{page.title}]]"


def build_index() -> int:
    pages = list_content_pages()

    grouped: dict[str, list[Page]] = defaultdict(list)
    for page in pages:
        grouped[page.category].append(page)

    order = [
        "root",
        "sources",
        "entities",
        "concepts",
        "topics",
        "syntheses",
        "comparisons",
        "queries",
        "reports",
        "system",
    ]
    remaining = sorted([name for name in grouped if name not in order])
    sections = order + remaining

    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Index",
        "",
        f"Updated: {now}",
        "",
        "This file is generated by `python3 tools/wiki.py build-index`.",
        "",
        "## Key Navigation",
        "",
        "- [[home|Home]] - Start here for workflows and conventions.",
        "- [[log|Log]] - Chronological record of ingests, queries, and lint passes.",
        "- [[system/schema|Schema]] - In-vault operating schema for this wiki.",
        "",
        "## Catalog",
        "",
    ]

    for section in sections:
        entries = sorted(grouped.get(section, []), key=lambda p: p.rel.as_posix())
        if not entries:
            continue
        header = section.replace("_", " ").title()
        lines.append(f"### {header} ({len(entries)})")
        lines.append("")
        for page in entries:
            lines.append(f"- {page_ref(page)} - {page.summary}")
        lines.append("")

    output = "\n".join(lines).rstrip() + "\n"
    index_path = WIKI_DIR / "index.md"
    previous = ""
    if index_path.exists():
        previous = index_path.read_text(encoding="utf-8")

    if output != previous:
        index_path.write_text(output, encoding="utf-8")
        print(f"Updated {index_path}")
    else:
        print("Index already up to date")

    return 0


def normalize_link_target(target: str) -> str:
    value = target.strip().lstrip("/")
    if value.endswith(".md"):
        value = value[:-3]
    return value


def lint(strict: bool) -> int:
    pages = list_content_pages()
    canonical = {page.rel.with_suffix("").as_posix(): page for page in pages}
    basename_map: dict[str, list[Page]] = defaultdict(list)
    for page in pages:
        basename_map[page.rel.stem].append(page)

    required_base = {"title", "type", "status", "created", "updated", "summary"}
    required_by_category = {
        "sources": {"source_id", "source_type", "origin", "ingested_on"},
    }

    missing_fields: list[str] = []
    broken_links: list[str] = []
    ambiguous_links: list[str] = []

    skip_link_validation = {"system"}

    inbound: dict[str, int] = defaultdict(int)

    for page in pages:
        if page.category not in {"system", "root"}:
            need = set(required_base)
            need.update(required_by_category.get(page.category, set()))
            missing = sorted(key for key in need if key not in page.frontmatter)
            if missing:
                missing_fields.append(
                    f"{page.rel.as_posix()}: missing {', '.join(missing)}"
                )

        for raw_target in page.links:
            if page.category in skip_link_validation:
                continue
            target = normalize_link_target(raw_target)
            if not target:
                continue

            if target in canonical:
                inbound[target] += 1
                continue

            if target in SPECIAL_LINK_TARGETS:
                continue

            if "/" not in target and target in basename_map:
                candidates = basename_map[target]
                if len(candidates) == 1:
                    inbound[candidates[0].rel.with_suffix("").as_posix()] += 1
                else:
                    ambiguous_links.append(
                        f"{page.rel.as_posix()}: [[{raw_target}]] matches {len(candidates)} pages"
                    )
                continue

            broken_links.append(f"{page.rel.as_posix()}: [[{raw_target}]]")

    orphan_exempt = {"home", "system/schema"}
    skip_link_validation = {"system/schema"}
    orphan_pages: list[str] = []
    for page in pages:
        key = page.rel.with_suffix("").as_posix()
        if key in orphan_exempt:
            continue
        if inbound.get(key, 0) == 0:
            orphan_pages.append(page.rel.as_posix())

    print(f"Pages checked: {len(pages)}")
    print(f"Missing frontmatter fields: {len(missing_fields)}")
    print(f"Broken links: {len(broken_links)}")
    print(f"Ambiguous links: {len(ambiguous_links)}")
    print(f"Orphans: {len(orphan_pages)}")

    if missing_fields:
        print("\nMissing fields:")
        for row in missing_fields:
            print(f"- {row}")

    if broken_links:
        print("\nBroken links:")
        for row in broken_links:
            print(f"- {row}")

    if ambiguous_links:
        print("\nAmbiguous links:")
        for row in ambiguous_links:
            print(f"- {row}")

    if orphan_pages:
        print("\nOrphan pages:")
        for row in orphan_pages:
            print(f"- {row}")

    has_errors = bool(missing_fields or broken_links or ambiguous_links)
    if strict:
        has_errors = has_errors or bool(orphan_pages)

    return 1 if has_errors else 0


def search(query: str, limit: int) -> int:
    terms = [token for token in re.findall(r"[A-Za-z0-9_\-]+", query.lower()) if token]
    if not terms:
        print("No query terms found")
        return 1

    pages = list_content_pages()
    scored: list[tuple[int, Page]] = []
    for page in pages:
        text = page.text.lower()
        title = page.title.lower()
        score = 0
        for term in terms:
            score += text.count(term)
            score += 5 * title.count(term)
        if score > 0:
            scored.append((score, page))

    scored.sort(key=lambda item: (-item[0], item[1].rel.as_posix()))
    if not scored:
        print("No results")
        return 0

    for score, page in scored[:limit]:
        print(f"{score:>3}  {page.rel.as_posix()}  {page.title}")
    return 0


def append_log_entry(
    operation: str,
    title: str,
    summary: str,
    pages: list[str],
    sources: list[str],
    notes: str,
) -> int:
    date = dt.datetime.now().strftime("%Y-%m-%d")
    log_path = WIKI_DIR / "log.md"
    if not log_path.exists():
        log_path.write_text("# Log\n\n", encoding="utf-8")

    rows = [f"## [{date}] {operation} | {title}", ""]
    rows.append(f"- Summary: {summary}")

    if sources:
        rows.append("- Sources: " + ", ".join(f"`{source}`" for source in sources))
    if pages:
        rendered_pages = []
        for page in pages:
            cleaned = page.strip().replace(".md", "")
            rendered_pages.append(f"[[{cleaned}]]")
        rows.append("- Pages touched: " + ", ".join(rendered_pages))
    if notes:
        rows.append(f"- Notes: {notes}")

    rows.append("")

    with log_path.open("a", encoding="utf-8") as handle:
        handle.write("\n".join(rows))

    print(f"Appended log entry to {log_path}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Markdown wiki maintenance tools")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("build-index", help="Regenerate wiki/index.md")

    lint_parser = sub.add_parser("lint", help="Validate links and metadata")
    lint_parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat orphan pages as failures",
    )

    search_parser = sub.add_parser("search", help="Search wiki content")
    search_parser.add_argument("query", help="Search query")
    search_parser.add_argument("--limit", type=int, default=10, help="Max results")

    log_parser = sub.add_parser("append-log", help="Append entry to wiki/log.md")
    log_parser.add_argument(
        "--operation", required=True, help="ingest|query|lint|other"
    )
    log_parser.add_argument("--title", required=True, help="Entry title")
    log_parser.add_argument("--summary", required=True, help="One-line summary")
    log_parser.add_argument("--page", action="append", default=[], help="Page path")
    log_parser.add_argument(
        "--source", action="append", default=[], help="Raw source path"
    )
    log_parser.add_argument("--notes", default="", help="Optional notes")

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "build-index":
        return build_index()
    if args.command == "lint":
        return lint(strict=args.strict)
    if args.command == "search":
        return search(args.query, args.limit)
    if args.command == "append-log":
        return append_log_entry(
            operation=args.operation,
            title=args.title,
            summary=args.summary,
            pages=args.page,
            sources=args.source,
            notes=args.notes,
        )

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
