#!/usr/bin/env python3
"""Generate thin provider adapters from canonical agent guidance."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from agent_profiles import Role, load_role  # noqa: E402
from llm_provider import resolve_provider  # noqa: E402
from agent_capabilities import (  # noqa: E402
    CAPABILITIES,
    claude_tools,
    codex_sandbox,
    profile_capabilities,
)

ROLES_DIR = ROOT / ".agents" / "roles"
CLAUDE_DIR = ROOT / ".claude" / "agents"
CODEX_DIR = ROOT / ".codex" / "agents"


class AdapterAccessError(OSError):
    """Adapter verification was blocked by filesystem access, not drift."""


def load_roles() -> list[Role]:
    roles: list[Role] = []
    for path in sorted(ROLES_DIR.glob("*.md")):
        role = load_role(path)
        if role.permission_profile not in CAPABILITIES:
            raise ValueError(
                f"{path}: unknown permission_profile {role.permission_profile!r}"
            )
        roles.append(role)
    if not roles:
        raise ValueError(f"no canonical roles found under {ROLES_DIR}")
    return roles


def _role_instruction(role: Role) -> str:
    rel = role.path.relative_to(ROOT).as_posix()
    return (
        "Resolve paths relative to the vault repository root, not the session's "
        "working directory. From a nested project directory, locate the ancestor "
        f"containing both `AGENTS.md` and `{rel}`. Before doing any other work, "
        f"read `{rel}` from that root in full and follow it as your "
        "canonical role instructions. Do not delegate or spawn another agent."
    )


def claude_manifest(role: Role) -> str:
    model = (
        resolve_provider(
            "claude",
            path=ROOT / "tools" / "llm.local.json",
            profile=role.model_profile,
            environ={},
        ).model
        or "inherit"
    )
    return (
        "---\n"
        f"name: {role.name}\n"
        f"description: {json.dumps(role.description)}\n"
        f"tools: {', '.join(claude_tools(profile_capabilities(role.permission_profile), scoped_shell=False))}\n"
        "disallowedTools: Agent, Task\n"
        f"model: {json.dumps(model)}\n"
        f"effort: {role.reasoning_effort}\n"
        "---\n\n"
        "<!-- Generated by tools/agents/generate-adapters.py; do not edit. -->\n\n"
        f"{_role_instruction(role)}\n"
    )


def codex_manifest(role: Role) -> str:
    model = resolve_provider(
        "codex",
        path=ROOT / "tools" / "llm.local.json",
        profile=role.model_profile,
        environ={},
    ).model
    model_setting = f"model = {json.dumps(model)}\n" if model else ""
    instruction = (
        f"{_role_instruction(role)} The role's file scope is an instruction boundary, "
        "not proof of hard isolation: a parent Codex session can override this custom "
        "agent's sandbox default. For hard isolation, launch through wiki-agent.py "
        "with an approved local runtime access profile."
    )
    perms = profile_capabilities(role.permission_profile)
    return (
        "# Generated by tools/agents/generate-adapters.py; do not edit.\n"
        f"name = {json.dumps(role.name)}\n"
        f"description = {json.dumps(role.description)}\n"
        f"{model_setting}"
        f"model_reasoning_effort = {json.dumps(role.reasoning_effort)}\n"
        f"sandbox_mode = {json.dumps(codex_sandbox(perms))}\n"
        "agents.enabled = false\n"
        'web_search = "disabled"\n'
        f"developer_instructions = {json.dumps(instruction)}\n"
    )


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def _sync(path: Path, expected: str, check: bool) -> bool:
    try:
        current = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    except OSError as exc:
        raise AdapterAccessError(f"cannot read {_display_path(path)}: {exc}") from exc
    if current == expected:
        return True
    if check:
        print(f"stale or missing: {_display_path(path)}")
        return False
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
    except OSError as exc:
        raise AdapterAccessError(f"cannot write {_display_path(path)}: {exc}") from exc
    print(f"wrote {_display_path(path)}")
    return True


def _check_adapter_set(directory: Path, suffix: str, expected: set[str]) -> bool:
    # Path.glob can silently report an unreadable directory as empty. Explicit
    # enumeration keeps blocked verification distinct from missing adapters.
    actual: set[str]
    try:
        actual = {
            path.name for path in directory.iterdir() if path.name.endswith(suffix)
        }
    except FileNotFoundError:
        actual = set()
    except OSError as exc:
        raise AdapterAccessError(
            f"cannot list {_display_path(directory)}: {exc}"
        ) from exc
    unexpected = sorted(actual - expected)
    if not unexpected:
        return True
    for name in unexpected:
        print(f"unexpected generated adapter: {_display_path(directory / name)}")
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail when generated adapters differ"
    )
    parser.add_argument(
        "--provider",
        choices=("claude", "codex"),
        help="check or sync only this provider (default: both)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Export adapters under this directory instead of the checkout",
    )
    args = parser.parse_args(argv)

    output = args.output_dir.resolve() if args.output_dir else ROOT
    claude_dir = output / ".claude" / "agents" if args.output_dir else CLAUDE_DIR
    codex_dir = output / ".codex" / "agents" if args.output_dir else CODEX_DIR
    try:
        roles = load_roles()
        ok = True
        if args.provider in (None, "claude"):
            ok &= _check_adapter_set(
                claude_dir, ".md", {f"{role.name}.md" for role in roles}
            )
            for role in roles:
                ok &= _sync(
                    claude_dir / f"{role.name}.md", claude_manifest(role), args.check
                )
        if args.provider in (None, "codex"):
            ok &= _check_adapter_set(
                codex_dir, ".toml", {f"{role.name}.toml" for role in roles}
            )
            for role in roles:
                ok &= _sync(
                    codex_dir / f"{role.name}.toml", codex_manifest(role), args.check
                )
    except AdapterAccessError as exc:
        print(f"BLOCKED adapter verification: {exc}", file=sys.stderr)
        return 2
    except ValueError as exc:
        parser.error(str(exc))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
