#!/usr/bin/env python3
"""Generate thin Claude and Codex manifests from canonical wiki-agent roles."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
ROLES_DIR = ROOT / ".agents" / "roles"
CLAUDE_DIR = ROOT / ".claude" / "agents"
CODEX_DIR = ROOT / ".codex" / "agents"

CLAUDE_TOOLS = {
    "read": "Read, Glob, Grep",
    "read-shell": "Read, Glob, Grep, Bash",
    "wiki-write": "Read, Glob, Grep, Bash, Write, Edit",
    "project-write": "Read, Glob, Grep, Bash, Write, Edit",
}
CLAUDE_MODELS = {"standard": "sonnet", "deep": "opus"}
CODEX_SANDBOX = {
    "read": "read-only",
    "read-shell": "read-only",
    "wiki-write": "workspace-write",
    "project-write": "workspace-write",
}


@dataclass(frozen=True)
class Role:
    path: Path
    name: str
    description: str
    permission_profile: str
    model_profile: str
    reasoning_effort: str


def _frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path}: missing YAML frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError(f"{path}: unterminated YAML frontmatter") from exc

    result: dict[str, str] = {}
    i = 1
    while i < end:
        line = lines[i]
        if not line or line.startswith(" ") or ":" not in line:
            i += 1
            continue
        key, raw = line.split(":", 1)
        value = raw.strip()
        if value in {">", ">-", "|", "|-"}:
            block: list[str] = []
            i += 1
            while i < end and (not lines[i] or lines[i].startswith(" ")):
                block.append(lines[i].strip())
                i += 1
            result[key] = " ".join(part for part in block if part)
            continue
        result[key] = value.strip("\"'")
        i += 1
    return result


def load_roles() -> list[Role]:
    roles: list[Role] = []
    for path in sorted(ROLES_DIR.glob("*.md")):
        data = _frontmatter(path)
        role = Role(
            path=path,
            name=data.get("name", ""),
            description=data.get("description", ""),
            permission_profile=data.get("permission_profile", ""),
            model_profile=data.get("model_profile", ""),
            reasoning_effort=data.get("reasoning_effort", ""),
        )
        if not role.name or not role.description:
            raise ValueError(f"{path}: name and description are required")
        if role.permission_profile not in CLAUDE_TOOLS:
            raise ValueError(
                f"{path}: unknown permission_profile {role.permission_profile!r}"
            )
        if role.model_profile not in CLAUDE_MODELS:
            raise ValueError(f"{path}: unknown model_profile {role.model_profile!r}")
        if role.reasoning_effort not in {"low", "medium", "high", "xhigh"}:
            raise ValueError(
                f"{path}: unknown reasoning_effort {role.reasoning_effort!r}"
            )
        roles.append(role)
    if not roles:
        raise ValueError(f"no canonical roles found under {ROLES_DIR}")
    return roles


def _role_instruction(role: Role) -> str:
    rel = role.path.relative_to(ROOT).as_posix()
    return (
        f"Before doing any other work, read `{rel}` in full and follow it as your "
        "canonical role instructions. Do not delegate or spawn another agent."
    )


def claude_manifest(role: Role) -> str:
    return (
        "---\n"
        f"name: {role.name}\n"
        f"description: {json.dumps(role.description)}\n"
        f"tools: {CLAUDE_TOOLS[role.permission_profile]}\n"
        "disallowedTools: Task\n"
        f"model: {CLAUDE_MODELS[role.model_profile]}\n"
        f"effort: {role.reasoning_effort}\n"
        "---\n\n"
        "<!-- Generated by tools/agents/generate-adapters.py; do not edit. -->\n\n"
        f"{_role_instruction(role)}\n"
    )


def codex_manifest(role: Role) -> str:
    instruction = _role_instruction(role)
    return (
        "# Generated by tools/agents/generate-adapters.py; do not edit.\n"
        f"name = {json.dumps(role.name)}\n"
        f"description = {json.dumps(role.description)}\n"
        f"model_reasoning_effort = {json.dumps(role.reasoning_effort)}\n"
        f"sandbox_mode = {json.dumps(CODEX_SANDBOX[role.permission_profile])}\n"
        f"developer_instructions = {json.dumps(instruction)}\n"
    )


def _sync(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return True
    if check:
        print(f"stale or missing: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail when generated adapters differ"
    )
    args = parser.parse_args(argv)

    ok = True
    for role in load_roles():
        ok &= _sync(CLAUDE_DIR / f"{role.name}.md", claude_manifest(role), args.check)
        ok &= _sync(CODEX_DIR / f"{role.name}.toml", codex_manifest(role), args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
